=== KohaAloha/kobli/install_misc/postupgrade/postupgrade_koha.xsd
<?xml version="1.0"?>
<xs:schema xmlns="http://koha-community.org" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://koha-community.org" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.1">
  <xs:annotation>
    <xs:documentation>Postupgrade actions xml schema</xs:documentation>
  </xs:annotation>


  <xs:element name="actions" type="ActionsType" nillable="false">
    <xs:annotation>
      <xs:documentation>Element indicating the set of actions</xs:documentation>
    </xs:annotation>
  </xs:element>

  <xs:complexType name="ActionsType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:element name="action" type="ActionType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ActionType">
    <xs:sequence>
      <xs:element name="question" type="StrLangType" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element name="answers" type="AnswersType" minOccurs="1"/>
      <xs:element name="response_comment" type="ResponseCommentType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="cmd" type="CmdType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="version" type="VersionType" use="required"/>
    <xs:attribute name="user" type="UserType" use="optional"/>
  </xs:complexType>

  <xs:simpleType name="VersionType">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:pattern value="[1-9]+\.[0-9]+(\.[0-9]+){1,2}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="UserType">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:pattern value="[a-zA-Z0-9\.\-_!\?]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="AnswersType">
    <xs:sequence minOccurs="2" maxOccurs="unbounded">
      <xs:element name="answer" type="AnswerType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="StrLangType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="lang" type="xs:string" use="optional" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="AnswerType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="lang" type="xs:string" use="optional" />
        <xs:attribute name="value" type="xs:boolean" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  
  <xs:complexType name="CmdType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="lang" type="xs:string" use="optional" />
        <xs:attribute name="md5" type="xs:string" use="optional"/>
        <xs:attribute name="crypt" type="CryptType" use="optional"/>
        <xs:attribute name="compress" type="CompressType" use="optional"/>
        <xs:attribute name="base64" type="xs:boolean" use="optional"/>
        <xs:attribute name="file" type="xs:string" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="ResponseCommentType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="lang" type="xs:string" use="optional" />
        <xs:attribute name="op" type="OpType" use="required" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="OpType">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:enumeration value="ok"/>
      <xs:enumeration value="nok"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="CryptType">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:pattern value="crypt:.+(:.+)?"/>
    </xs:restriction>
  </xs:simpleType>

    <xs:simpleType name="CompressType">
    <xs:restriction base="xs:string">
      <xs:whiteSpace value="collapse"/>
      <xs:enumeration value="gzip"/>
      <xs:enumeration value="bzip2"/>
    </xs:restriction>
  </xs:simpleType>


</xs:schema>

=== KohaAloha/kobli/install_misc/postupgrade/postupgrade_koha.xml
<?xml version="1.0" encoding="UTF-8"?>

<actions xmlns="http://koha-community.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation= "./postupgrade_koha.xsd">
    <action version="1.8.1">
        <question lang="es-ES">Debido a la actualización del marc21 a las revisiones 13 y 14 en Kobli, ¿Quiere sobreescribir la plantilla DEFAULT para marc21 con la nueva de INGLÉS (sobreescribirá la existente, haga copia de seguridad de la bbdd)?</question>
        <question lang="en">With the upgrade of marc21 to versions 13 and 14 in Kobli. Do you want to overwrite the DEFAULT framework with the new one in ENGLISH (please make a backup of the database before)?</question>
        <answers>
            <answer lang="es-ES" value="true">Sí</answer>
            <answer lang="en" value="true">Yes</answer>
            <answer value="false">No</answer>
        </answers>
        <response_comment op="ok" lang="es-ES">Actualizada plantilla DEFAULT en inglés</response_comment>
        <response_comment op="nok" lang="es-ES">Error al actualizar la plantilla DEFAULT en inglés</response_comment>
        <response_comment op="ok" lang="en">English DEFAULT framework updated</response_comment>
        <response_comment op="nok" lang="en">Error updating english DEFAULT framework</response_comment>
        <cmd base64="true" md5="5e14b85a4a66bc3ed46f748b86925bc1">ZWNobyAiREVMRVRFIEZST00gbWFyY190YWdfc3RydWN0dXJlIFdIRVJFIGZyYW1l
d29ya2NvZGU9Jyc7IERFTEVURSBGUk9NIG1hcmNfc3ViZmllbGRfc3RydWN0dXJl
IFdIRVJFIGZyYW1ld29ya2NvZGU9Jyc7IiB8ICRiYmRkY29uZXggJiYgJGJiZGRj
b25leCA8ICRQV0QvaW5zdGFsbGVyL2RhdGEvJG5vZGVfY29uZmlnX2RiX3NjaGVt
ZS9lbi9tYXJjZmxhdm91ci9tYXJjMjEvbWFuZGF0b3J5L21hcmMyMV9mcmFtZXdv
cmtfREVGQVVMVC5zcWwK</cmd>
    </action>
    <action version="1.8.1">
        <question lang="es-ES">Debido a la actualización del marc21 a las revisiones 13 y 14 en Kobli, ¿Quiere sobreescribir la plantilla FastAdd para marc21 con la nueva de INGLÉS (sobreescribirá la existente, haga copia de seguridad de la bbdd)?</question>
        <question lang="en">With the upgrade of marc21 to versions 13 and 14 in Kobli. Do you want to overwrite the FastAdd framework with the new one in ENGLISH (please make a backup of the database before)?</question>
        <answers>
            <answer lang="es-ES" value="true">Sí</answer>
            <answer lang="en" value="true">Yes</answer>
            <answer value="false">No</answer>
        </answers>
        <response_comment op="ok" lang="es-ES">Actualizada plantilla FastAdd en inglés</response_comment>
        <response_comment op="nok" lang="es-ES">Error al actualizar la plantilla FastAdd en inglés</response_comment>
        <response_comment op="ok" lang="en">English FastAdd framework updated</response_comment>
        <response_comment op="nok" lang="en">Error updating english FastAdd framework</response_comment>
        <cmd base64="true" md5="ddb09c62f578feeb81e4cb448023a2e9">IGVjaG8gIkRFTEVURSBGUk9NIG1hcmNfdGFnX3N0cnVjdHVyZSBXSEVSRSBmcmFt
ZXdvcmtjb2RlPSdGQSc7IERFTEVURSBGUk9NIG1hcmNfc3ViZmllbGRfc3RydWN0
dXJlIFdIRVJFIGZyYW1ld29ya2NvZGU9J0ZBJzsiIHwgJGJiZGRjb25leCAmJiAk
YmJkZGNvbmV4IDwgJFBXRC9pbnN0YWxsZXIvZGF0YS8kbm9kZV9jb25maWdfZGJf
c2NoZW1lL2VuL21hcmNmbGF2b3VyL21hcmMyMS9vcHRpb25hbC9tYXJjMjFfZmFz
dGFkZF9mcmFtZXdvcmsuc3Fs</cmd>
    </action>
    <action version="1.8.1">
        <question lang="es-ES">Debido a la actualización del marc21 a las revisiones 13 y 14 en Kobli, ¿Quiere sobreescribir el resto de plantillas para marc21 con la nueva de INGLÉS (sobreescribirá la existente, haga copia de seguridad de la bbdd)?</question>
        <question lang="en">With the upgrade of marc21 to versions 13 and 14 in Kobli. Do you want to overwrite the remaining frameworks with the new ones in ENGLISH (please make a backup of the database before)?</question>
        <answers>
            <answer lang="es-ES" value="true">Sí</answer>
            <answer lang="en" value="true">Yes</answer>
            <answer value="false">No</answer>
        </answers>
        <response_comment op="ok" lang="es-ES">Actualizadas resto de plantillas en inglés</response_comment>
        <response_comment op="nok" lang="es-ES">Error al actualizar el resto de plantillas en inglés</response_comment>
        <response_comment op="ok" lang="en">Remaining english frameworks updated</response_comment>
        <response_comment op="nok" lang="en">Error updating remaining english frameworks</response_comment>
        <cmd base64="true" md5="ba2cf529cab4ec87361ea56a700c4347">ZWNobyAiREVMRVRFIEZST00gYmlibGlvX2ZyYW1ld29yayBXSEVSRSBmcmFtZXdv
cmtjb2RlIE5PVCBJTiAoJycsJ0ZBJyk7IERFTEVURSBGUk9NIG1hcmNfdGFnX3N0
cnVjdHVyZSBXSEVSRSBmcmFtZXdvcmtjb2RlIE5PVCBJTiAoJycsJ0ZBJyk7IERF
TEVURSBGUk9NIG1hcmNfc3ViZmllbGRfc3RydWN0dXJlIFdIRVJFIGZyYW1ld29y
a2NvZGUgTk9UIElOICgnJywnRkEnKTsiIHwgJGJiZGRjb25leCAmJiAkYmJkZGNv
bmV4IDwgJFBXRC9pbnN0YWxsZXIvZGF0YS8kbm9kZV9jb25maWdfZGJfc2NoZW1l
L2VuL21hcmNmbGF2b3VyL21hcmMyMS9vcHRpb25hbC9tYXJjMjFfc2ltcGxlX2Jp
Yl9mcmFtZXdvcmtzLnNxbA==</cmd>
    </action>
    <action version="1.8.1">
        <question lang="es-ES">Debido a la actualización del marc21 a las revisiones 13 y 14 en Kobli, ¿Quiere sobreescribir los indicadores para marc21 con la nueva de INGLÉS (sobreescribirá los existentes, haga copia de seguridad de la bbdd)?</question>
        <question lang="en">With the upgrade of marc21 to versions 13 and 14 in Kobli. Do you want to overwrite the indicators with the new ones in ENGLISH (please make a backup of the database before)?</question>
        <answers>
            <answer lang="es-ES" value="true">Sí</answer>
            <answer lang="en" value="true">Yes</answer>
            <answer value="false">No</answer>
        </answers>
        <response_comment op="ok" lang="es-ES">Actualizados indicadores en inglés</response_comment>
        <response_comment op="nok" lang="es-ES">Error al actualizar los indicadores en inglés</response_comment>
        <response_comment op="ok" lang="en">English indicators updated</response_comment>
        <response_comment op="nok" lang="en">Error updating english indicators</response_comment>
        <cmd base64="true" md5="9b9a5d142c723d5612c3c7d5d1a0b58b">JGJiZGRjb25leCA8ICRQV0QvaW5zdGFsbGVyL2RhdGEvJG5vZGVfY29uZmlnX2Ri
X3NjaGVtZS9lbi9tYXJjZmxhdm91ci9tYXJjMjEvbWFuZGF0b3J5L21hcmMyMV9p
bmRpY2F0b3JzLnNxbA==</cmd>
    </action>
    <action version="1.8.1">
        <question lang="es-ES">Debido a la actualización del marc21 a las revisiones 13 y 14 en Kobli, ¿Quiere sobreescribir la plantilla DEFAULT para marc21 con la nueva de ESPAÑOL (sobreescribirá la existente, haga copia de seguridad de la bbdd)?</question>
        <question lang="en">With the upgrade of marc21 to versions 13 and 14 in Kobli. Do you want to overwrite the DEFAULT framework with the new one in SPANISH (please make a backup of the database before)?</question>
        <answers>
            <answer lang="es-ES" value="true">Sí</answer>
            <answer lang="en" value="true">Yes</answer>
            <answer value="false">No</answer>
        </answers>
        <response_comment op="ok" lang="es-ES">Actualizada plantilla DEFAULT en español</response_comment>
        <response_comment op="nok" lang="es-ES">Error al actualizar la plantilla DEFAULT en español</response_comment>
        <response_comment op="ok" lang="en">Spanish DEFAULT framework updated</response_comment>
        <response_comment op="nok" lang="en">Error updating spanish DEFAULT framework</response_comment>
        <cmd base64="true" md5="bb22fab0caa5c939fe000ec2d1a31339">ZWNobyAiREVMRVRFIEZST00gbWFyY190YWdfc3RydWN0dXJlIFdIRVJFIGZyYW1l
d29ya2NvZGU9Jyc7IERFTEVURSBGUk9NIG1hcmNfc3ViZmllbGRfc3RydWN0dXJl
IFdIRVJFIGZyYW1ld29ya2NvZGU9Jyc7IiB8ICRiYmRkY29uZXggJiYgJGJiZGRj
b25leCA8ICRQV0QvaW5zdGFsbGVyL2RhdGEvJG5vZGVfY29uZmlnX2RiX3NjaGVt
ZS9lcy1FUy9tYXJjZmxhdm91ci9tYXJjMjEvb2JsaWdhdG9yaW8vbWFyYzIxX2Zy
YW1ld29ya19ERUZBVUxULnNxbA==</cmd>
    </action>
    <action version="1.8.1">
        <question lang="es-ES">Debido a la actualización del marc21 a las revisiones 13 y 14 en Kobli, ¿Quiere sobreescribir la plantilla FastAdd para marc21 con la nueva de ESPAÑOL (sobreescribirá la existente, haga copia de seguridad de la bbdd)?</question>
        <question lang="en">With the upgrade of marc21 to versions 13 and 14 in Kobli. Do you want to overwrite the FastAdd framework with the new one in SPANISH (please make a backup of the database before)?</question>
        <answers>
            <answer lang="es-ES" value="true">Sí</answer>
            <answer lang="en" value="true">Yes</answer>
            <answer value="false">No</answer>
        </answers>
        <response_comment op="ok" lang="es-ES">Actualizada plantilla FastAdd en español</response_comment>
        <response_comment op="nok" lang="es-ES">Error al actualizar la plantilla FastAdd en español</response_comment>
        <response_comment op="ok" lang="en">Spanish FastAdd framework updated</response_comment>
        <response_comment op="nok" lang="en">Error updating spanish FastAdd framework</response_comment>
        <cmd base64="true" md5="0e6813fb73e6145c68dc14331c629f18">I2VjaG8gIkRFTEVURSBGUk9NIG1hcmNfdGFnX3N0cnVjdHVyZSBXSEVSRSBmcmFt
ZXdvcmtjb2RlPSdGQSc7IERFTEVURSBGUk9NIG1hcmNfc3ViZmllbGRfc3RydWN0
dXJlIFdIRVJFIGZyYW1ld29ya2NvZGU9J0ZBJzsiIHwgJGJiZGRjb25leCAmJiAk
YmJkZGNvbmV4IDwgJFBXRC9pbnN0YWxsZXIvZGF0YS8kbm9kZV9jb25maWdfZGJf
c2NoZW1lL2VzLUVTL21hcmNmbGF2b3VyL21hcmMyMS9vcGNpb25hbC9tYXJjMjFf
ZmFzdGFkZF9mcmFtZXdvcmsuc3Fs</cmd>
    </action>
    <action version="1.8.1">
        <question lang="es-ES">Debido a la actualización del marc21 a las revisiones 13 y 14 en Kobli, ¿Quiere sobreescribir el resto de plantillas para marc21 con la nueva de ESPAÑOL (sobreescribirá la existente, haga copia de seguridad de la bbdd)?</question>
